nodeLinker: node-modules

# Mantiene la estructura clásica de Yarn 1
nmMode: classic

# Evita que Yarn modifique package.json automáticamente
enableImmutableInstalls: false

# Evita que Yarn genere archivos innecesarios
enableGlobalCache: true
